### ISSUE TITLE
Trap hack not working

### ISSUE THREAD

**Issue by mxswd** [CommBank/maestro#12]
When running the maestro-example, traps are not being caught.

```
[{1}:0] tuple: ['The following errors occured: Customer accounts...
cascading.pipe.OperatorException: [_pipe_0+_pipe_1][com.twitter.scalding.RichPipe.eachTo(RichPipe.scala:480)] operator Each failed executing operation
	at cascading.flow.stream.FunctionEachStage.receive(FunctionEachStage.java:107)
	at cascading.flow.stream.FunctionEachStage.receive(FunctionEachStage.java:39)
	at cascading.flow.stream.FunctionEachStage$1.collect(FunctionEachStage.java:80)
	at cascading.tuple.TupleEntryCollector.safeCollect(TupleEntryCollector.java:119)
	at cascading.tuple.TupleEntryCollector.add(TupleEntryCollector.java:107)
	at com.twitter.scalding.FlatMapFunction$$anonfun$operate$2.apply(Operations.scala:41)
	at com.twitter.scalding.FlatMapFunction$$anonfun$operate$2.apply(Operations.scala:39)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at com.twitter.scalding.FlatMapFunction.operate(Operations.scala:39)
	at cascading.flow.stream.FunctionEachStage.receive(FunctionEachStage.java:99)
	at cascading.flow.stream.FunctionEachStage.receive(FunctionEachStage.java:39)
	at cascading.flow.stream.FunctionEachStage$1.collect(FunctionEachStage.java:80)
	at cascading.tuple.TupleEntryCollector.safeCollect(TupleEntryCollector.java:119)
	at cascading.tuple.TupleEntryCollector.add(TupleEntryCollector.java:107)
	at com.twitter.scalding.FlatMapFunction$$anonfun$operate$2.apply(Operations.scala:41)
	at com.twitter.scalding.FlatMapFunction$$anonfun$operate$2.apply(Operations.scala:39)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at com.twitter.scalding.FlatMapFunction.operate(Operations.scala:39)
	at cascading.flow.stream.FunctionEachStage.receive(FunctionEachStage.java:99)
	at cascading.flow.stream.FunctionEachStage.receive(FunctionEachStage.java:39)
	at cascading.flow.stream.Stage.receive(Stage.java:30)
	at cascading.flow.stream.SourceStage.map(SourceStage.java:102)
	at cascading.flow.stream.SourceStage.run(SourceStage.java:58)
	at cascading.flow.hadoop.FlowMapper.run(FlowMapper.java:127)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:428)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:340)
	at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:231)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.RuntimeException: trap
	at scala.sys.package$.error(package.scala:27)
	at au.com.cba.omnia.maestro.core.scalding.Errors$$anonfun$handle$2.apply(Errors.scala:48)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at com.twitter.scalding.FlatMapFunction.operate(Operations.scala:39)
	at cascading.flow.stream.FunctionEachStage.receive(FunctionEachStage.java:99)
	... 33 more
```

**Comment by SamRoberts** [comment]
Ran maestro example with some bad values in the customer data, they were trapped and printed out in the errors file just fine. Didn't see @shmookey had been assigned to this, though, so I'll just leave this comment here. :smile:

**Comment by SamRoberts** [comment]
Additional comment for @shmookey: we refactored `load` to use the TypedPipe's `addTrap` method some time ago.

**Comment by shmookey** [comment]
Appears to work fine for me, closing.
