### ISSUE TITLE
Scalding counter fails often

### ISSUE THREAD

**Issue by stephanh** [CommBank/maestro#300]
Not sure why but on some map tasks for some loads trying to access the `FlowDef` on the individual mapppers to increase the filter counter fails. Scalding stores the `FlowDef`s in a HashMap and uses the job id to look them up. Below is the execption:
```
2015-01-12 13:34:50,292 ERROR cascading.flow.stream.TrapHandler: caught Throwable, no trap available, rethrowing
cascading.pipe.OperatorException: [com.twitter.scalding.M...][com.twitter.scalding.RichPipe.eachTo(RichPipe.scala:478)] operator Each failed executing operation
	at cascading.flow.stream.FunctionEachStage.receive(FunctionEachStage.java:107)
	at cascading.flow.stream.FunctionEachStage.receive(FunctionEachStage.java:39)
	at cascading.flow.stream.FunctionEachStage$1.collect(FunctionEachStage.java:80)
	at cascading.tuple.TupleEntryCollector.safeCollect(TupleEntryCollector.java:145)
	at cascading.tuple.TupleEntryCollector.add(TupleEntryCollector.java:133)
	at au.com.cba.omnia.maestro.core.task.ExtractTime.operate(LoadHelper.scala:265)
	at cascading.flow.stream.FunctionEachStage.receive(FunctionEachStage.java:99)
	at cascading.flow.stream.FunctionEachStage.receive(FunctionEachStage.java:39)
	at cascading.flow.stream.SourceStage.map(SourceStage.java:102)
	at cascading.flow.stream.SourceStage.run(SourceStage.java:58)
	at cascading.flow.hadoop.FlowMapper.run(FlowMapper.java:130)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:417)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:332)
	at org.apache.hadoop.mapred.Child$4.run(Child.java:268)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:396)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1438)
	at org.apache.hadoop.mapred.Child.main(Child.java:262)
Caused by: java.lang.RuntimeException: Error in job deployment, the FlowProcess for unique id UniqueID(1490058012982771712) isn't available
	at scala.sys.package$.error(package.scala:27)
	at com.twitter.scalding.RuntimeStats$$anonfun$getFlowProcessForUniqueId$2.apply(Stats.scala:121)
	at com.twitter.scalding.RuntimeStats$$anonfun$getFlowProcessForUniqueId$2.apply(Stats.scala:121)
	at scala.Option.getOrElse(Option.scala:120)
	at com.twitter.scalding.RuntimeStats$.getFlowProcessForUniqueId(Stats.scala:120)
	at com.twitter.scalding.Stat$$anon$1.flowProcess$lzycompute(Stats.scala:50)
	at com.twitter.scalding.Stat$$anon$1.flowProcess(Stats.scala:50)
	at com.twitter.scalding.Stat$$anon$1.incBy(Stats.scala:52)
	at com.twitter.scalding.Stat$class.inc(Stats.scala:30)
	at com.twitter.scalding.Stat$$anon$1.inc(Stats.scala:48)
	at au.com.cba.omnia.maestro.core.task.LoadHelper$$anonfun$5$$anonfun$apply$5.apply(LoadHelper.scala:162)
	at au.com.cba.omnia.maestro.core.task.LoadHelper$$anonfun$5$$anonfun$apply$5.apply(LoadHelper.scala:162)
	at scala.Option.foreach(Option.scala:236)
	at au.com.cba.omnia.maestro.core.task.LoadHelper$$anonfun$5.apply(LoadHelper.scala:162)
	at au.com.cba.omnia.maestro.core.task.LoadHelper$$anonfun$5.apply(LoadHelper.scala:159)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at com.twitter.scalding.FlatMapFunction.operate(Operations.scala:47)
	at cascading.flow.stream.FunctionEachStage.receive(FunctionEachStage.java:99)
	... 17 more
2015-01-12 13:34:50,294 ERROR cascading.flow.stream.TrapHandler: caught Throwable, no trap available, rethrowing
cascading.pipe.OperatorException: [com.twitter.scalding.M...][com.twitter.scalding.RichPipe.eachTo(RichPipe.scala:478)] operator Each failed executing operation
	at cascading.flow.stream.FunctionEachStage.receive(FunctionEachStage.java:107)
	at cascading.flow.stream.FunctionEachStage.receive(FunctionEachStage.java:39)
	at cascading.flow.stream.FunctionEachStage$1.collect(FunctionEachStage.java:80)
	at cascading.tuple.TupleEntryCollector.safeCollect(TupleEntryCollector.java:145)
	at cascading.tuple.TupleEntryCollector.add(TupleEntryCollector.java:133)
	at au.com.cba.omnia.maestro.core.task.ExtractTime.operate(LoadHelper.scala:265)
	at cascading.flow.stream.FunctionEachStage.receive(FunctionEachStage.java:99)
	at cascading.flow.stream.FunctionEachStage.receive(FunctionEachStage.java:39)
	at cascading.flow.stream.SourceStage.map(SourceStage.java:102)
	at cascading.flow.stream.SourceStage.run(SourceStage.java:58)
	at cascading.flow.hadoop.FlowMapper.run(FlowMapper.java:130)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:417)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:332)
	at org.apache.hadoop.mapred.Child$4.run(Child.java:268)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:396)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1438)
	at org.apache.hadoop.mapred.Child.main(Child.java:262)
Caused by: java.lang.RuntimeException: Error in job deployment, the FlowProcess for unique id UniqueID(1490058012982771712) isn't available
	at scala.sys.package$.error(package.scala:27)
	at com.twitter.scalding.RuntimeStats$$anonfun$getFlowProcessForUniqueId$2.apply(Stats.scala:121)
	at com.twitter.scalding.RuntimeStats$$anonfun$getFlowProcessForUniqueId$2.apply(Stats.scala:121)
	at scala.Option.getOrElse(Option.scala:120)
	at com.twitter.scalding.RuntimeStats$.getFlowProcessForUniqueId(Stats.scala:120)
	at com.twitter.scalding.Stat$$anon$1.flowProcess$lzycompute(Stats.scala:50)
	at com.twitter.scalding.Stat$$anon$1.flowProcess(Stats.scala:50)
	at com.twitter.scalding.Stat$$anon$1.incBy(Stats.scala:52)
	at com.twitter.scalding.Stat$class.inc(Stats.scala:30)
	at com.twitter.scalding.Stat$$anon$1.inc(Stats.scala:48)
	at au.com.cba.omnia.maestro.core.task.LoadHelper$$anonfun$5$$anonfun$apply$5.apply(LoadHelper.scala:162)
	at au.com.cba.omnia.maestro.core.task.LoadHelper$$anonfun$5$$anonfun$apply$5.apply(LoadHelper.scala:162)
	at scala.Option.foreach(Option.scala:236)
	at au.com.cba.omnia.maestro.core.task.LoadHelper$$anonfun$5.apply(LoadHelper.scala:162)
	at au.com.cba.omnia.maestro.core.task.LoadHelper$$anonfun$5.apply(LoadHelper.scala:159)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at com.twitter.scalding.FlatMapFunction.operate(Operations.scala:47)
	at cascading.flow.stream.FunctionEachStage.receive(FunctionEachStage.java:99)
	... 17 more
2015-01-12 13:34:50,295 ERROR cascading.flow.stream.SourceStage: caught throwable
cascading.pipe.OperatorException: [com.twitter.scalding.M...][com.twitter.scalding.RichPipe.eachTo(RichPipe.scala:478)] operator Each failed executing operation
	at cascading.flow.stream.FunctionEachStage.receive(FunctionEachStage.java:107)
	at cascading.flow.stream.FunctionEachStage.receive(FunctionEachStage.java:39)
	at cascading.flow.stream.FunctionEachStage$1.collect(FunctionEachStage.java:80)
	at cascading.tuple.TupleEntryCollector.safeCollect(TupleEntryCollector.java:145)
	at cascading.tuple.TupleEntryCollector.add(TupleEntryCollector.java:133)
	at au.com.cba.omnia.maestro.core.task.ExtractTime.operate(LoadHelper.scala:265)
	at cascading.flow.stream.FunctionEachStage.receive(FunctionEachStage.java:99)
	at cascading.flow.stream.FunctionEachStage.receive(FunctionEachStage.java:39)
	at cascading.flow.stream.SourceStage.map(SourceStage.java:102)
	at cascading.flow.stream.SourceStage.run(SourceStage.java:58)
	at cascading.flow.hadoop.FlowMapper.run(FlowMapper.java:130)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:417)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:332)
	at org.apache.hadoop.mapred.Child$4.run(Child.java:268)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:396)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1438)
	at org.apache.hadoop.mapred.Child.main(Child.java:262)
Caused by: java.lang.RuntimeException: Error in job deployment, the FlowProcess for unique id UniqueID(1490058012982771712) isn't available
	at scala.sys.package$.error(package.scala:27)
	at com.twitter.scalding.RuntimeStats$$anonfun$getFlowProcessForUniqueId$2.apply(Stats.scala:121)
	at com.twitter.scalding.RuntimeStats$$anonfun$getFlowProcessForUniqueId$2.apply(Stats.scala:121)
	at scala.Option.getOrElse(Option.scala:120)
	at com.twitter.scalding.RuntimeStats$.getFlowProcessForUniqueId(Stats.scala:120)
	at com.twitter.scalding.Stat$$anon$1.flowProcess$lzycompute(Stats.scala:50)
	at com.twitter.scalding.Stat$$anon$1.flowProcess(Stats.scala:50)
	at com.twitter.scalding.Stat$$anon$1.incBy(Stats.scala:52)
	at com.twitter.scalding.Stat$class.inc(Stats.scala:30)
	at com.twitter.scalding.Stat$$anon$1.inc(Stats.scala:48)
	at au.com.cba.omnia.maestro.core.task.LoadHelper$$anonfun$5$$anonfun$apply$5.apply(LoadHelper.scala:162)
	at au.com.cba.omnia.maestro.core.task.LoadHelper$$anonfun$5$$anonfun$apply$5.apply(LoadHelper.scala:162)
	at scala.Option.foreach(Option.scala:236)
	at au.com.cba.omnia.maestro.core.task.LoadHelper$$anonfun$5.apply(LoadHelper.scala:162)
	at au.com.cba.omnia.maestro.core.task.LoadHelper$$anonfun$5.apply(LoadHelper.scala:159)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at com.twitter.scalding.FlatMapFunction.operate(Operations.scala:47)
	at cascading.flow.stream.FunctionEachStage.receive(FunctionEachStage.java:99)
	... 17 more
2015-01-12 13:34:50,314 INFO org.apache.hadoop.mapred.TaskLogsTruncater: Initializing logs' truncater with mapRetainSize=-1 and reduceRetainSize=-1
2015-01-12 13:34:50,316 WARN org.apache.hadoop.mapred.Child: Error running child
cascading.pipe.OperatorException: [com.twitter.scalding.M...][com.twitter.scalding.RichPipe.eachTo(RichPipe.scala:478)] operator Each failed executing operation
	at cascading.flow.stream.FunctionEachStage.receive(FunctionEachStage.java:107)
	at cascading.flow.stream.FunctionEachStage.receive(FunctionEachStage.java:39)
	at cascading.flow.stream.FunctionEachStage$1.collect(FunctionEachStage.java:80)
	at cascading.tuple.TupleEntryCollector.safeCollect(TupleEntryCollector.java:145)
	at cascading.tuple.TupleEntryCollector.add(TupleEntryCollector.java:133)
	at au.com.cba.omnia.maestro.core.task.ExtractTime.operate(LoadHelper.scala:265)
	at cascading.flow.stream.FunctionEachStage.receive(FunctionEachStage.java:99)
	at cascading.flow.stream.FunctionEachStage.receive(FunctionEachStage.java:39)
	at cascading.flow.stream.SourceStage.map(SourceStage.java:102)
	at cascading.flow.stream.SourceStage.run(SourceStage.java:58)
	at cascading.flow.hadoop.FlowMapper.run(FlowMapper.java:130)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:417)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:332)
	at org.apache.hadoop.mapred.Child$4.run(Child.java:268)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:396)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1438)
	at org.apache.hadoop.mapred.Child.main(Child.java:262)
Caused by: java.lang.RuntimeException: Error in job deployment, the FlowProcess for unique id UniqueID(1490058012982771712) isn't available
	at scala.sys.package$.error(package.scala:27)
	at com.twitter.scalding.RuntimeStats$$anonfun$getFlowProcessForUniqueId$2.apply(Stats.scala:121)
	at com.twitter.scalding.RuntimeStats$$anonfun$getFlowProcessForUniqueId$2.apply(Stats.scala:121)
	at scala.Option.getOrElse(Option.scala:120)
	at com.twitter.scalding.RuntimeStats$.getFlowProcessForUniqueId(Stats.scala:120)
	at com.twitter.scalding.Stat$$anon$1.flowProcess$lzycompute(Stats.scala:50)
	at com.twitter.scalding.Stat$$anon$1.flowProcess(Stats.scala:50)
	at com.twitter.scalding.Stat$$anon$1.incBy(Stats.scala:52)
	at com.twitter.scalding.Stat$class.inc(Stats.scala:30)
	at com.twitter.scalding.Stat$$anon$1.inc(Stats.scala:48)
	at au.com.cba.omnia.maestro.core.task.LoadHelper$$anonfun$5$$anonfun$apply$5.apply(LoadHelper.scala:162)
	at au.com.cba.omnia.maestro.core.task.LoadHelper$$anonfun$5$$anonfun$apply$5.apply(LoadHelper.scala:162)
	at scala.Option.foreach(Option.scala:236)
	at au.com.cba.omnia.maestro.core.task.LoadHelper$$anonfun$5.apply(LoadHelper.scala:162)
	at au.com.cba.omnia.maestro.core.task.LoadHelper$$anonfun$5.apply(LoadHelper.scala:159)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at com.twitter.scalding.FlatMapFunction.operate(Operations.scala:47)
	at cascading.flow.stream.FunctionEachStage.receive(FunctionEachStage.java:99)
	... 17 more
2015-01-12 13:34:50,318 INFO org.apache.hadoop.mapred.Task: Runnning cleanup for the task
```

**Comment by vineethvarghese** [comment]
FlowDef is really in a WeakHashMap rather than a HashMap. In this case, if the rows to be filtered are on top, we have no issues.

**Comment by stephanh** [comment]
Not sure what that means?

**Comment by vineethvarghese** [comment]
It means it is susceptible to being GCed. I modified the scalding source to use a HashMap and things work as expected. I am going to play around using a SoftReference but it is interesting that no one else has reported this issue with the scalding library.

**Comment by SamRoberts** [comment]
Wouldn't we ensure that we hold a hard reference to the key, to keep it from being GC'd?

**Comment by vineethvarghese** [comment]
Nope we can't because we don't create them in the first place. In the scalding library the object com.twitter.scalding.RuntimeStats is the culprit. In its addFlowProcess method (where the map is populated), the keys are created by splitting a String. The key will obviously be "available" for GC once the method is executed. To test this theory, I modified that method to add all the keys into a Set (in addition to the FlowProcessMap) so that we maintain a hard reference and when tested, the StatCounter worked as expected i.e. the keys weren't GCed.

**Comment by vineethvarghese** [comment]
Fix will be available with scalding 0.13.1. I would prefer we leave this ticket open till we actually upgrade and sort out this issue.

**Comment by vineethvarghese** [comment]
Scalding 0.13.1 is out https://github.com/twitter/scalding/releases/tag/0.13.1

**Comment by vineethvarghese** [comment]
@stephanh When do you think we will be moving to 0.13.1?
