### ISSUE TITLE
Issue with running Hive in unit tests after migrating to CDH5.2

### ISSUE THREAD

**Issue by ranjanin08** [CommBank/maestro#348]
We are experiencing issues in running unit tests which test Hive queries involving a join after migrating to CDH5.2. 
```
[16:37:11][Step 2/5] Failed to detect a valid hadoop home directory
[16:37:11][Step 2/5] java.io.IOException: HADOOP_HOME or hadoop.home.dir are not set.
[16:37:11][Step 2/5]     at org.apache.hadoop.util.Shell.checkHadoopHome(Shell.java:302)
[16:37:11][Step 2/5]     at org.apache.hadoop.util.Shell.<clinit>(Shell.java:327)
[16:37:11][Step 2/5]     at org.apache.hadoop.hive.conf.HiveConf$ConfVars.findHadoopBinary(HiveConf.java:1171)
[16:37:11][Step 2/5]     at org.apache.hadoop.hive.conf.HiveConf$ConfVars.<clinit>(HiveConf.java:247)
[16:37:11][Step 2/5]     at au.com.cba.omnia.thermometer.hive.HiveSupport$class.$init$(HiveSupport.scala:41)
[16:37:11][Step 2/5]     at au.com.cba.omnia.etl.test.EtlTest.<init>(EtlTest.scala:46)
[16:37:11][Step 2/5]     at au.com.cba.omnia.etl.features.gdw.TestSpec.<init>(TestSpec.scala:17)
[16:37:11][Step 2/5]     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[16:37:11][Step 2/5]     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
[16:37:11][Step 2/5]     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[16:37:11][Step 2/5]     at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
```

An example of where this problem can be seen is HiveTesting in nagara.etl.features-gdw repo on stash.

**Comment by rowandavies** [comment]
I think you mentioned earlier that one or two other people had a similar issue - can you ask them to "comment" here the with the details to help investigate the issue?

**Comment by rowandavies** [comment]
Can you create an ordinary, remote branch on stash so I can easily clone it to investigate?

**Comment by anukrishnank** [comment]
I am also facing similar issue . Test cases are failing when hive query is having join condition . But in my case the error is different .

java.io.IOException: Cannot run program "/usr/bin/hadoop" (in directory "/private/tmp/hadoop/test-baf1c685-36a4-4e26-9da1-0737b0978605/mapred/user"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
	at java.lang.Runtime.exec(Runtime.java:617)
	at java.lang.Runtime.exec(Runtime.java:450)
	at org.apache.hadoop.hive.ql.exec.mr.MapredLocalTask.execute(MapredLocalTask.java:258)
	at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:153)
	at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(TaskRunner.java:85)
	at org.apache.hadoop.hive.ql.Driver.launchTask(Driver.java:1516)
	at org.apache.hadoop.hive.ql.Driver.execute(Driver.java:1283)
	at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:1101)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:924)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:914)

**Comment by rowandavies** [comment]
@anukrishnank Do you have a project on stash that leads to this error?  If so, can you make a branch available to me so I can experiment to see why this is happening?

**Comment by rowandavies** [comment]
Also, are you manually setting the path at some point?

**Comment by rowandavies** [comment]
@ranjanin08  @anukrishnank Okay, I had a preliminary look and this seems likely due to changes in `org.apache.hadoop.hive`, but it's hard to say for sure.  If so, this may take some time to resolve since we may need to involve Cloudera.

Meanwhile, if there are any situations where tests with hive joins do succeed with CDH5.2, it would be good to post details here.

**Comment by rowandavies** [comment]
Quote from @anukrishnank:  
> Regarding the issue #348 please find the stash link https://stash.odp.cba/projects/OMETL/repos/etl.commsee-kiakatching/browse?at=kiakatching_dev

**Comment by patelh** [comment]
@anukrishnank disable map join optimization:

            hiveConf.set("hive.auto.convert.join","false");
            hiveConf.set("hive.auto.convert.join.noconditionaltask","false");

**Comment by ranjanin08** [comment]
@greyamigo  gave it a try on one of the branches that we were using to reproduce the problem and it seems to do the trick. I will close this issue after we test on the cluster (for a normal run) and are comfortable with the results.

**Comment by stephanh** [comment]
Thank you @patelh very helpful!

**Comment by anukrishnank** [comment]
@patelh tried the parameters in the code and it seems to do the trick.  Thank you

**Comment by stephanh** [comment]
I updated the test hive-site.xml in Thermometer to set these settings so this should now be fixed for the latest version of maestro.
