### ISSUE TITLE
Database does not exist: default 

### ISSUE THREAD

**Issue by maxmithun** [CommBank/maestro#379]
Issue while executing mulitple test cases, "Database does not exist: default" 

Execution is using 2 control tables one at execution side and other at source. 
Execution step includes : 
1) Sqoop Import
2) Load
3) Hive Paritioned Table
4) Hive Intermediate Table

```
        at org.apache.hadoop.hive.metastore.ObjectStore.getMDatabase(ObjectStore.java:495)
        at org.apache.hadoop.hive.metastore.ObjectStore.getDatabase(ObjectStore.java:506)
        at sun.reflect.GeneratedMethodAccessor558.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.apache.hadoop.hive.metastore.RawStoreProxy.invoke(RawStoreProxy.java:108)
        at com.sun.proxy.$Proxy311.getDatabase(Unknown Source)
        at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.get_database(HiveMetaStore.java:805)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.apache.hadoop.hive.metastore.RetryingHMSHandler.invoke(RetryingHMSHandler.java:106)
        at com.sun.proxy.$Proxy313.get_database(Unknown Source)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.getDatabase(HiveMetaStoreClient.java:960)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:90)
        at com.sun.proxy.$Proxy314.getDatabase(Unknown Source)
        at org.apache.hadoop.hive.ql.metadata.Hive.getDatabase(Hive.java:1188)
        at org.apache.hadoop.hive.ql.parse.BaseSemanticAnalyzer.getDatabase(BaseSemanticAnalyzer.java:1140)
        at org.apache.hadoop.hive.ql.parse.BaseSemanticAnalyzer.getDatabase(BaseSemanticAnalyzer.java:1135)
        at org.apache.hadoop.hive.ql.parse.FunctionSemanticAnalyzer.addEntities(FunctionSemanticAnalyzer.java:171)
        at org.apache.hadoop.hive.ql.parse.FunctionSemanticAnalyzer.analyzeCreateFunction(FunctionSemanticAnalyzer.java:88)
        at org.apache.hadoop.hive.ql.parse.FunctionSemanticAnalyzer.analyzeInternal(FunctionSemanticAnalyzer.java:61)
        at org.apache.hadoop.hive.ql.parse.BaseSemanticAnalyzer.analyze(BaseSemanticAnalyzer.java:204)
        at org.apache.hadoop.hive.ql.Driver.compile(Driver.java:434)
        at org.apache.hadoop.hive.ql.Driver.compile(Driver.java:332)
        at org.apache.hadoop.hive.ql.Driver.compileInternal(Driver.java:988)
        at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:1053)
        at org.apache.hadoop.hive.ql.Driver.run(Driver.java:924)
        at org.apache.hadoop.hive.ql.Driver.run(Driver.java:914)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anonfun$10$$anonfun$apply$7$$anonfun$11.apply(Hive.scala:288)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anonfun$10$$anonfun$apply$7$$anonfun$11.apply(Hive.scala:288)
        at au.com.cba.omnia.omnitool.Result$.safe(Result.scala:153)
        at au.com.cba.omnia.omnitool.ResultantMonad$$anonfun$point$1.apply(ResultantMonad.scala:37)
        at au.com.cba.omnia.omnitool.ResultantMonad$$anonfun$point$1.apply(ResultantMonad.scala:37)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rPoint$1.apply(Hive.scala:308)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rPoint$1.apply(Hive.scala:308)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive.run(Hive.scala:61)
        at au.com.cba.omnia.maestro.core.scalding.RichExecutionObject$$anonfun$fromHive$1$$anonfun$apply$7.apply(RichExecution.scala:93)
        at au.com.cba.omnia.maestro.core.scalding.RichExecutionObject$$anonfun$fromHive$1$$anonfun$apply$7.apply(RichExecution.scala:92)
        at com.twitter.scalding.Execution$FutureConst$$anonfun$runStats$1$$anonfun$1.apply(Execution.scala:251)
        at com.twitter.scalding.Execution$FutureConst$$anonfun$runStats$1$$anonfun$1.apply(Execution.scala:251)
        at scala.util.Try$.apply(Try.scala:161)
        at com.twitter.scalding.Execution$FutureConst$$anonfun$runStats$1.apply(Execution.scala:251)
        at com.twitter.scalding.Execution$FutureConst$$anonfun$runStats$1.apply(Execution.scala:250)
        at com.twitter.scalding.Execution$MapEvalCache.getOrElseInsert(Execution.scala:224)
        at com.twitter.scalding.Execution$FutureConst.runStats(Execution.scala:250)
        at com.twitter.scalding.Execution$FlatMapped$$anonfun$runStats$2$$anonfun$3.apply(Execution.scala:268)
        at com.twitter.scalding.Execution$FlatMapped$$anonfun$runStats$2$$anonfun$3.apply(Execution.scala:266)
        at scala.util.Success$$anonfun$map$1.apply(Try.scala:206)
        at scala.util.Try$.apply(Try.scala:161)
        at scala.util.Success.map(Try.scala:206)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

FAILED: SemanticException [Error 10072]: Database does not exist: default
15/04/28 12:36:38 ERROR ql.Driver: FAILED: SemanticException [Error 10072]: Database does not exist: default
org.apache.hadoop.hive.ql.parse.SemanticException: Database does not exist: default
        at org.apache.hadoop.hive.ql.parse.BaseSemanticAnalyzer.getDatabase(BaseSemanticAnalyzer.java:1146)
        at org.apache.hadoop.hive.ql.parse.BaseSemanticAnalyzer.getDatabase(BaseSemanticAnalyzer.java:1135)
        at org.apache.hadoop.hive.ql.parse.FunctionSemanticAnalyzer.addEntities(FunctionSemanticAnalyzer.java:171)
        at org.apache.hadoop.hive.ql.parse.FunctionSemanticAnalyzer.analyzeCreateFunction(FunctionSemanticAnalyzer.java:88)
        at org.apache.hadoop.hive.ql.parse.FunctionSemanticAnalyzer.analyzeInternal(FunctionSemanticAnalyzer.java:61)
        at org.apache.hadoop.hive.ql.parse.BaseSemanticAnalyzer.analyze(BaseSemanticAnalyzer.java:204)
        at org.apache.hadoop.hive.ql.Driver.compile(Driver.java:434)
        at org.apache.hadoop.hive.ql.Driver.compile(Driver.java:332)
        at org.apache.hadoop.hive.ql.Driver.compileInternal(Driver.java:988)
        at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:1053)
        at org.apache.hadoop.hive.ql.Driver.run(Driver.java:924)
        at org.apache.hadoop.hive.ql.Driver.run(Driver.java:914)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anonfun$10$$anonfun$apply$7$$anonfun$11.apply(Hive.scala:288)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anonfun$10$$anonfun$apply$7$$anonfun$11.apply(Hive.scala:288)
        at au.com.cba.omnia.omnitool.Result$.safe(Result.scala:153)
        at au.com.cba.omnia.omnitool.ResultantMonad$$anonfun$point$1.apply(ResultantMonad.scala:37)
        at au.com.cba.omnia.omnitool.ResultantMonad$$anonfun$point$1.apply(ResultantMonad.scala:37)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rPoint$1.apply(Hive.scala:308)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rPoint$1.apply(Hive.scala:308)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anon$1$$anonfun$rBind$1.apply(Hive.scala:310)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive.run(Hive.scala:61)
        at au.com.cba.omnia.maestro.core.scalding.RichExecutionObject$$anonfun$fromHive$1$$anonfun$apply$7.apply(RichExecution.scala:93)
        at au.com.cba.omnia.maestro.core.scalding.RichExecutionObject$$anonfun$fromHive$1$$anonfun$apply$7.apply(RichExecution.scala:92)
        at com.twitter.scalding.Execution$FutureConst$$anonfun$runStats$1$$anonfun$1.apply(Execution.scala:251)
        at com.twitter.scalding.Execution$FutureConst$$anonfun$runStats$1$$anonfun$1.apply(Execution.scala:251)
        at scala.util.Try$.apply(Try.scala:161)
        at com.twitter.scalding.Execution$FutureConst$$anonfun$runStats$1.apply(Execution.scala:251)
        at com.twitter.scalding.Execution$FutureConst$$anonfun$runStats$1.apply(Execution.scala:250)
        at com.twitter.scalding.Execution$MapEvalCache.getOrElseInsert(Execution.scala:224)
        at com.twitter.scalding.Execution$FutureConst.runStats(Execution.scala:250)
        at com.twitter.scalding.Execution$FlatMapped$$anonfun$runStats$2$$anonfun$3.apply(Execution.scala:268)
        at com.twitter.scalding.Execution$FlatMapped$$anonfun$runStats$2$$anonfun$3.apply(Execution.scala:266)
        at scala.util.Success$$anonfun$map$1.apply(Try.scala:206)
        at scala.util.Try$.apply(Try.scala:161)
        at scala.util.Success.map(Try.scala:206)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.hadoop.hive.ql.parse.SemanticException: Database does not exist: default
        at org.apache.hadoop.hive.ql.parse.BaseSemanticAnalyzer.getDatabase(BaseSemanticAnalyzer.java:1142)
        ... 57 more

```

**Comment by stephanh** [comment]
@maxmithun have you tried setting the parallel settings to false as @rowandavies suggested?

If that doesn't work can you please provide a minimal reproducible test for this.

**Comment by maxmithun** [comment]
@stephanh  i have tried the setting suggested by @rowandavies but didnt workout. 

you can take the farlo-clm project and uncomment 2 test and execute it, which will produce the issue

**Comment by rowandavies** [comment]
I'm looking into this, as support.

**Comment by rowandavies** [comment]
@maxmithun I uncommented two tests (and commented out the ojdbc dependency).  It results in the exceptions you posted.  But, it's not obvious what the issue is, and the code is sufficiently complicated and unfamiliar to me that it would be a lot of work for me to even to narrow down the possibilities of which code is the source of the issue.  Also, it's unclear what steps you've taken to determine that the issue results from Maestro libraries rather than the code in etl.farlo-clm itself.

If you'd like this issue resolved, can you please use your knowledge of the project to remove all the code that isn't related to the issue, leaving only the minimal code that results in the issue, then place this in a branch that I can access?  If you're unsure of how to go about this, we can discuss it this afternoon.

I'd add that the information you're providing about the issue seems somewhat minimal, which gives the impression that you don't want to help too much with resolving the issue.  In future we hope that issue reports will aim to be as helpful as possible.

**Comment by stephanh** [comment]
@maxmithun @rowandavies this issue has been inactive for a while. Can it be closed?

**Comment by maxmithun** [comment]
@stephanh  closing the  issue, since it got resolved by removing the hive UDF creation method called multiple times used for generating hashkey
