### ISSUE TITLE
ViewExecution.viewHive fails to overwrite partitions

### ISSUE THREAD

**Issue by SajeevAr** [CommBank/maestro#426]
The following issues were faced while overwriting partitions using viewHive (with append mode as false). eg. viewHive(conf.transformationTable, pipe, false). These issues are related to the fix for CommBank/maestro#382. etl-util version used is 1.14.0-20150625002151-e89a7bc. 

1. If the table location doesn't exist, viewHive will fail with a ResultException as shown below. This occurs as Line:101 in HiveTable.scala tries to list all the files inside a directory that does not exist. But unit test is not getting failed in this case (which is not expected), the failure is seen only while running the jar. But while trying to explicitly list the same directory (outside viewHive), test fails as expected (Line:123 in CarBaseExecution.scala). The code is pushed into stash repo etl.commsee-car (branch: car_phase2).
 
2. MSCK REPAIR TABLE (Line:122 in HiveTable.scala) is trying to repair the table in default database instead of actual database. This causes NoSuchObjectException (exception shown below) while running the jar, but the job finishes with status 0.

3. As per the current approach, it seems MSCK REPAIR TABLE is not needed, as no partitions are added or deleted while overwriting. Only the files within a partition are removed and added, which does not require MSCK REPAIR TABLE query. In the above case 2, the partitions were modified as expected even though this query has failed.

4. The current approach could fail if there is no data to overwrite in an existing partition. In that case, no parquet files will be created, but the existing files in the partition needs to be removed, which may not happen as per the current approach.

**Comment by SajeevAr** [comment]
The following exception occurs if the table location doesn't exist.
```15/07/15 11:23:10 INFO Configuration.deprecation: io.bytes.per.checksum is deprecated. Instead, use dfs.bytes-per-checksum
15/07/15 11:23:10 ERROR car.CseCcaVerifiedItemsExecution$: error running execution
au.com.cba.omnia.maestro.scalding.ResultException: HDFS operation failed: '<table_location>' must be a directory!
	at au.com.cba.omnia.maestro.scalding.RichExecutionObject.fromHdfs(RichExecution.scala:53)
	at au.com.cba.omnia.maestro.hive.PartitionedHiveTable$$anonfun$writeExecution$2.apply(HiveTable.scala:101)
	at au.com.cba.omnia.maestro.hive.PartitionedHiveTable$$anonfun$writeExecution$2.apply(HiveTable.scala:98)
	at com.twitter.scalding.Execution$FlatMapped$$anonfun$runStats$2$$anonfun$3.apply(Execution.scala:268)
	at com.twitter.scalding.Execution$FlatMapped$$anonfun$runStats$2$$anonfun$3.apply(Execution.scala:267)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:236)
	at scala.util.Try$.apply(Try.scala:191)
	at scala.util.Success.map(Try.scala:236)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)```

**Comment by SajeevAr** [comment]
The following error occurs while running MSCK REPAIR TABLE query.

```15/07/13 11:38:54 WARN conf.HiveConf: DEPRECATED: Configuration property hive.metastore.local no longer has any effect. Make sure to provide a valid value for hive.metastore.uris if you are connecting to a remote metastore.
15/07/13 11:38:54 ERROR metadata.Hive: NoSuchObjectException(message:default.CSE_CCA_APP_transformation table not found)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$get_table_result$get_table_resultStandardScheme.read(ThriftHiveMetastore.java:29338)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$get_table_result$get_table_resultStandardScheme.read(ThriftHiveMetastore.java:29306)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$get_table_result.read(ThriftHiveMetastore.java:29237)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_get_table(ThriftHiveMetastore.java:1036)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.get_table(ThriftHiveMetastore.java:1022)
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.getTable(HiveMetaStoreClient.java:1008)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:90)
	at com.sun.proxy.$Proxy19.getTable(Unknown Source)
	at org.apache.hadoop.hive.ql.metadata.Hive.getTable(Hive.java:999)
	at org.apache.hadoop.hive.ql.metadata.Hive.getTable(Hive.java:973)
	at org.apache.hadoop.hive.ql.metadata.HiveMetaStoreChecker.checkTable(HiveMetaStoreChecker.java:187)
	at org.apache.hadoop.hive.ql.metadata.HiveMetaStoreChecker.checkMetastore(HiveMetaStoreChecker.java:97)
	at org.apache.hadoop.hive.ql.exec.DDLTask.msck(DDLTask.java:1968)
	at org.apache.hadoop.hive.ql.exec.DDLTask.execute(DDLTask.java:349)
	at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:153)
	at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(TaskRunner.java:85)
	at org.apache.hadoop.hive.ql.Driver.launchTask(Driver.java:1516)
	at org.apache.hadoop.hive.ql.Driver.execute(Driver.java:1283)
	at org.apache.hadoop.hive.ql.Driver.runInternal(Driver.java:1101)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:924)
	at org.apache.hadoop.hive.ql.Driver.run(Driver.java:914)
        at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anonfun$query$1.apply(Hive.scala:256)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive$$anonfun$query$1.apply(Hive.scala:249)
	at au.com.cba.omnia.ebenezer.scrooge.hive.Hive.run(Hive.scala:61)
	at au.com.cba.omnia.maestro.scalding.RichExecutionObject$$anonfun$fromHive$1$$anonfun$apply$3.apply(RichExecution.scala:82)
	at au.com.cba.omnia.maestro.scalding.RichExecutionObject$$anonfun$fromHive$1$$anonfun$apply$3.apply(RichExecution.scala:81)
	at com.twitter.scalding.Execution$FutureConst$$anonfun$runStats$1$$anonfun$1.apply(Execution.scala:252)
	at com.twitter.scalding.Execution$FutureConst$$anonfun$runStats$1$$anonfun$1.apply(Execution.scala:252)
	at scala.util.Try$.apply(Try.scala:191)
	at com.twitter.scalding.Execution$FutureConst$$anonfun$runStats$1.apply(Execution.scala:252)
	at com.twitter.scalding.Execution$FutureConst$$anonfun$runStats$1.apply(Execution.scala:251)
	at com.twitter.scalding.Execution$MapEvalCache.getOrElseInsert(Execution.scala:225)
	at com.twitter.scalding.Execution$FutureConst.runStats(Execution.scala:251)
	at com.twitter.scalding.Execution$FlatMapped$$anonfun$runStats$2$$anonfun$3.apply(Execution.scala:269)
	at com.twitter.scalding.Execution$FlatMapped$$anonfun$runStats$2$$anonfun$3.apply(Execution.scala:267)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:236)
	at scala.util.Try$.apply(Try.scala:191)
	at scala.util.Success.map(Try.scala:236)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

15/07/13 11:38:54 INFO log.PerfLogger: </PERFLOG method=runTasks start=1436751534740 end=1436751534899 duration=159 from=org.apache.hadoop.hive.ql.Driver>
15/07/13 11:38:54 INFO log.PerfLogger: </PERFLOG method=Driver.execute start=1436751534729 end=1436751534899 duration=170 from=org.apache.hadoop.hive.ql.Driver>
15/07/13 11:38:54 INFO ql.Driver: OK
15/07/13 11:38:54 INFO log.PerfLogger: <PERFLOG method=releaseLocks from=org.apache.hadoop.hive.ql.Driver>
15/07/13 11:38:54 INFO log.PerfLogger: </PERFLOG method=releaseLocks start=1436751534900 end=1436751534900 duration=0 from=org.apache.hadoop.hive.ql.Driver>
15/07/13 11:38:54 INFO log.PerfLogger: </PERFLOG method=Driver.run start=1436751533753 end=1436751534900 duration=1147 from=org.apache.hadoop.hive.ql.Driver>
15/07/13 11:38:54 INFO log.PerfLogger: <PERFLOG method=releaseLocks from=org.apache.hadoop.hive.ql.Driver>
15/07/13 11:38:54 INFO log.PerfLogger: </PERFLOG method=releaseLocks start=1436751534907 end=1436751534907 duration=0 from=org.apache.hadoop.hive.ql.Driver>
15/07/13 11:38:54 INFO zookeeper.ZooKeeper: Session: 0x34e3507875aaa5e closed
15/07/13 11:38:54 INFO zookeeper.ClientCnxn: EventThread shut down
15/07/13 11:38:54 INFO Configuration.deprecation: io.bytes.per.checksum is deprecated. Instead, use dfs.bytes-per-checksum
Exited job au.com.cba.omnia.etl.commsee.car.CseCcaAppExecution (0.2.0-20150713004736-e43d88f-SNAPSHOT) at Mon Jul 13 11:39:00 AEST 2015 with status 0```

**Comment by stephanh** [comment]
Are you sure a repair table is not needed? The files that make up a partition have changed.

With regards to 4, if no data is written how do we know which partition has changed? This is to overwrite specific partitions in an existing table not the whole table. If you don't write any data how do we know which partition to overwrite?

If you want to get rid of all the previous data you should delete the table beforehand?

**Comment by jithinjohn** [comment]
@SajeevAr I also got error mentioned in case 1, when a table already existed and corresponding HDFS location was not there. But I am able to create a new table and load data in overwrite mode successfully. Could you please confirm  whether you tried to  create a new hive table

**Comment by stephanh** [comment]
@SajeevAr do you know why the underlying directory has been deleted?

**Comment by SajeevAr** [comment]
@stephanh In my understanding, MSCK REPAIR TABLE will add metadata about partitions to Hive metastore, for partitions for which such metadata doesn't already exist. So if new partitions are not added and only if the files within the partitions have changed, I think MSCK REPAIR TABLE is not needed while using Hive. I was referring to 'Recover Partitions (MSCK REPAIR TABLE)' section in https://cwiki.apache.org/confluence/display/Hive/LanguageManual+DDL
But I'm not quite sure how this behaves with ViewExecution.viewHive. This may require further analysis. 

I agree with you on Case 4. Though I don't have a specific use case to explain, I just thought about a situation where we have to overwrite some existing partitions (not the whole table), when the input pipe can be empty. I was wondering if such scenarios could be handled.

**Comment by SajeevAr** [comment]
@jithinjohn Yes, this issue happens only while loading data into a table in overwrite mode, whose external location does not exist. 

@stephanh As part of testing, the HDFS directories may be cleared without dropping the table and may reload the table with new data. The issue was noted because the same scenario was working fine in the previous implementation.

**Comment by stephanh** [comment]
No we can't handle 4. Without information how do we know which partitions you want to override?

**Comment by stephanh** [comment]
@SajeevAr I think I fixed the bugs. I ended up removing `MSCK REPAIR TABLE` if the hive documentation is correct then you are right and we don't need it. Can you please the latest version and let me know if it fixes your problems.

**Comment by SajeevAr** [comment]
Thanks @stephanh . I shall test with the latest maestro version and shall provide an update.

**Comment by SajeevAr** [comment]
@stephanh Published util.etl in local with the maestro version 2.12.1-20150716022418-87386a0 and tested. The issues mentioned in case 1, 2 and 3 are fixed in this version.

**Comment by stephanh** [comment]
Thank you @SajeevAr! And thank you for raising such a detailed bug report!
