### ISSUE TITLE
Investigate thread pool issues in tests

### ISSUE THREAD

**Issue by rowandavies** [CommBank/maestro#544]
See:  

https://travis-ci.org/CommBank/maestro/builds/352794832#L3932-L5728

```
Execution request rejected by java.util.concurrent.ThreadPoolExecutor@5dfbdf41[Shutting down, pool size = 3, active threads = 2, queued tasks = 0, completed tasks = 7]
Executing scala.concurrent.impl.CallbackRunnable@533c3a8e in caller thread instead (name=pool-4216-thread-2, id=21914)
Execution of scala.concurrent.impl.CallbackRunnable@533c3a8e complete
[repeat 600 times]
```
Also: https://travis-ci.org/CommBank/maestro/builds/185105878#L3257

```
java.util.concurrent.RejectedExecutionException: Task scala.concurrent.impl.CallbackRunnable@379bc7e9 rejected from java.util.concurrent.ThreadPoolExecutor@5461ae84[Shutting down, pool size = 2, active threads = 1, queued tasks = 0, completed tasks = 11]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2048)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:821)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1372)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$1.execute(ExecutionContextImpl.scala:136)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.complete(Promise.scala:55)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

And: http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/7u40-b43/java/util/concurrent/ThreadPoolExecutor.java/#1355

**Comment by rowandavies** [comment]
It seems to be in the RichExecution tests.
